version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2017
environment:
  matrix:
  - nodejs_version: 10
install:
- cmd: powershell Install-Product node $env:nodejs_version
- sh: nvm install $nodejs_version
- npm install
build_script:
- npm run build
test_script:
- node --version
- npm --version
cache:
- node_modules -> package.json
matrix:
  fast_finish: true
